apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: mertpolatace/task:latest
        ports:
        - containerPort: 8080
        env:
        - name: MYSQL_DATABASE_DB
          value: TaskDB
        - name: MYSQL_DATABASE_HOST
          value: mysql.default.svc.cluster.local
        - name: MYSQL_DATABASE_PASSWORD
          value: secret
        - name: MYSQL_DATABASE_USER
          value: user
        - name: MYSQL_ROOT_PASSWORD
          value: my-secret

---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
