name: kubernetes

on:
  push:
    branches:
      - "main"
              

jobs:
  deploy_to_kubernetes_cluster:
    needs: push_docker_image_to_github_packages
    name: Set Kubernetes Context
    uses: azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBE_CONFIG }} # Use secret (https://developer.github.com/actions/managing-workflows/storing-secrets/)
    run: |
      sed -i'' -e 's/IMAGE_LABEL/${{ github.sha }}/g' deployment.yml
      kubectl apply -f deployment.yml
