name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_and_deploy:

    runs-on: linux ghcr.io 

    steps:
    - uses: actions/checkout@v3

    - name: Log in to Docker registry
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin your-registry-url

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag 127.0.0.1:5000/my-image-name:$(date +%s)

    - name: Push Docker image to registry
      run: docker push 127.0.0.1:5000/my-image-name:$(date +%s)

  deploy:
    name: Deploy to Kubernetes
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Create kubeconfig
      run: |
        mkdir ${HOME}/.kube
        echo ${{ secrets.KUBE_CONFIG }} | base64 --decode > ${HOME}/.kube/config
    - name: Use context
      run: kubectl config use-context 
    - name: Deploy to K8s
      run: kubectl apply -f .k8s/
