name: Docker Iage CI for GHCR

on: 
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Build and push the image
        run : |
          docker login --username mert2m --password ${{ secrets.GH_PAT }} ghcr.io
          docker build . --tag ghcr.io/mert2m/actions-runner-controller:latest
          docker push ghcr.io/mert2m/actions-runner-controller:latest

  build-and-deploy:
      runs-on: self-hosted
      steps:
      - name: deploy on your cluster
        run: |
          kubectl --kubeconfig /Users/mertpolat/.kube apply -f task-deployment-service.yaml
