name: Docker Iage CI for GHCR

on: 
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Build and push the image
        run : |
          docker login --username mert2m --password ${{ secrets.GH_PAT }} ghcr.io
          docker build . --tag ghcr.io/mert2m/actions-runner-controller:latest
          docker push ghcr.io/mert2m/actions-runner-controller:latest

  deploy:
    name: Deploy to Kubernetes
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Create kubeconfig
      run: |
        mkdir ${HOME}/.kube
        echo ${{ secrets.KUBE_CONFIG }} | base64 --decode > ${HOME}/.kube/config
    - name: Use context
      run: kubectl config use-context kind-kind-for-ingress
    - name: Deploy to K8s
      run: kubectl apply -f .k8s/task-deployment-service
