name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_and_deploy:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Log in to Docker registry
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin your-registry-url

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag localhost:5001/my-image-name:$(date +%s)

    - name: Push Docker image to registry
      run: docker push localhost:5001/my-image-name:$(date +%s)

    - name: Deploy to Kubernetes
      run: |
          kubectl apply -f .k8s/
