name: Build and push Docker image

on:
  push:
    tags:
      - '*'
    branches:
      - 'main'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      # Other steps omitted for brevity

      - name: Set tag from git describe
        id: set-tag
        run: echo "tag=$(git describe --tags HEAD)" >> $GITHUB_ENV

      # Other steps omitted for brevity

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/actions-runner-controller:${{ env.tag }}

