name: ci

on:
  push:
    branches:
      - main

jobs:
  build_and_push_image:  # New job name
    runs-on: self-hosted
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
      - name: Build and push to local registry
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true  # Assuming you want to push to the local registry
          tags: localhost:5000/name/app:latest
      - name: Inspect
        run: |
          docker buildx imagetools inspect localhost:5000/name/app:latest

  deploy_to_kubernetes_cluster:  # Assuming the previous job successfully builds the image
    needs: build_and_push_image  # Updated dependency
    name: Set Kubernetes Context
    uses: azure/k8s-set-context@v1
    with:
      method: kubeconfig
      kubeconfig: ${{ secrets.KUBE_CONFIG_SECURE }}  # Use a secure way to store kubeconfig

    # ... (Steps to deploy the application to the Kubernetes cluster)
